name: Weekly Model Training
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
jobs:
  train_model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install pandas numpy scikit-learn xgboost joblib
      - name: Run Training
        run: python trainer.py
      - name: Commit and Push new model
        run: |
          git config user.name "Auto Trainer Bot"
          git config user.email "actions@github.com"
          git add model/model.pkl
          git commit -m "Weekly Model Update"
          git push
        continue-on-error: true
